# Server configuration
server.port=${PORT:8080}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:drive_mentor}?sslmode=${DB_SSL_MODE:disable}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Settings
drivementor.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
drivementor.jwt.expiration=86400000

# Hikari Database Connection Settings
spring.datasource.hikari.initialization-fail-timeout=-1
